version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
  web:
    ports:
      - "8000:80"
###< doctrine/doctrine-bundle ###

# ###> symfony/mailer ###
#   mailer:
#     image: schickling/mailcatcher
#     ports: ["1025", "1080"]
# ###< symfony/mailer ###
