<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD6WUn5F\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD6WUn5F/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerD6WUn5F.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerD6WUn5F\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerD6WUn5F\App_KernelTestDebugContainer([
    'container.build_hash' => 'D6WUn5F',
    'container.build_id' => 'e47e2441',
    'container.build_time' => 1687203479,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD6WUn5F');
