<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV9CgzTB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV9CgzTB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV9CgzTB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV9CgzTB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV9CgzTB\App_KernelDevDebugContainer([
    'container.build_hash' => 'V9CgzTB',
    'container.build_id' => '81b47541',
    'container.build_time' => 1687203521,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV9CgzTB');
